### ISSUE TITLE
How to install this package with npm/yarn/bower ?

### ISSUE THREAD

**Issue by oscarotero** [Templarian/MaterialDesign-SVG#1]
Hi
I've tried to install this package using yarn or npm but I get an error because there's no package.json file:

```
yarn add Templarian/MaterialDesign-SVG
error Couldn't find manifest in "https://github.com/Templarian/MaterialDesign-SVG.git".
```

I think we should create a `package.json` file and register the package in npm repository, in the same way than mdi

Thanks for this great work.

**Comment by Templarian** [comment]
Yea, on my to do list. Been a little busy, will get this added shortly to bower/NPM.

**Comment by Templarian** [comment]
Published to bower as `mdi-svg`. [Messaged](https://github.com/conundrumer/mdi-svg/issues/1) the person that has the NPM name `mdi-svg` to try and get ownership for consistency.

Will give it a few days, if not I'll think of another name for this package.

**Comment by Templarian** [comment]
@oscarotero Sorry about the delay on this, been really busy this summer. NPM and Bower both use `mdi-svg`. Will update the documentation shortly explaining this repo and how to use it.

**Comment by oscarotero** [comment]
🎉 thank you!
