### ISSUE TITLE
mdiCheckBold is missing

### ISSUE THREAD

**Issue by YuriGor** [Templarian/MaterialDesign-SVG#11]
Hi, I am trying to import [this check icon](https://materialdesignicons.com/icon/check-bold)

`import { mdiCheckBold } from '@mdi/js';`

but looks like there is in such icon

![image](https://user-images.githubusercontent.com/6861317/54082623-d6ebab80-4329-11e9-9dc0-c5a6b6106f95.png)

**Comment by PeterShaggyNoble** [comment]
It will be available in the next release, coming soon.

**Comment by YuriGor** [comment]
When will be the next release? 
I need that damn bold check mark tomorrow, so it's better to grab SVG path string right from the site?

**Comment by YuriGor** [comment]
Ok, I just used SVG path string directly for now.

**Comment by Templarian** [comment]
@YuriGor Yep, working on the release right now, my goal is to have it out this weekend. 😃
