### ISSUE TITLE
Ignored by webpack externals

### ISSUE THREAD

**Issue by mmintel** [Templarian/MaterialDesign-SVG#12]
Hi there!

Thanks for this awesome package! I try to implement this into a vue library and want to exclude this from my build files. Tried to add this to my `vue.config.js`

```
  chainWebpack: (config) => {
    config.externals({
      ...config.get('externals'),
      'lodash': 'lodash',
      '@mdi/svg': {
        commonjs: '@mdi/svg',
        commonjs2: '@mdi/svg',
        umd: '@mdi/svg',
        amd: 'svg',
        root: 'svg'
      },
    })
```

which works for `lodash` but doesn't work for this package here. Do you know what's wrong? Simply putting it like `'@mdi/svg': '@mdi/svg'` also doesnt work.

**Comment by Templarian** [comment]
Almost never monitor the distribution repo for this package. If you're still running into this issue can you please open it at the main repo: https://github.com/Templarian/MaterialDesign/issues/

The community will see it there. I personally don't know the answer to this.
