### ISSUE TITLE
Community icons

### ISSUE THREAD

**Issue by Extarys** [Templarian/MaterialDesign-SVG#14]
Is there a way to include the community icons in mdi/js - mdi/svg ? I can't find an easy way to use them in Vue and most interesting icons are community ones :)
Is it a licensing issue?

**Comment by Templarian** [comment]
@Extarys https://dev.materialdesignicons.com/getting-started/vuejs

Probably found it, but above are the docs for VueJS. Still working on the new site.

We don't really monitor the NPM distribution repos. Make sure to post all questions to the main repo: https://github.com/Templarian/MaterialDesign
