### ISSUE TITLE
Some icons are missing on the correct version

### ISSUE THREAD

**Issue by djcaesar9114** [Templarian/MaterialDesign-SVG#15]
Hello,
I'm using the `mdue` package for my Vue project. It allows to use MaterialDesignIcons in my components. I thought I didn't have all the icons because of the version used in `mdue`, so I updated the version (see my pull request here: https://github.com/pepsighan/mdue/pull/6 ).
Actually it doesn't work either. I'm using version 6.5.95 because it's the one I see on the official website (https://materialdesignicons.com/). As you can see in the list (https://pictogrammers.github.io/@mdi/font/6.5.95/), some icons available on the website are not here, for example this one: https://materialdesignicons.com/icon/paperclip-plus. 
Could anybody please explain what happens here?
Thanks in advance :)

**Comment by Templarian** [comment]
We don't really monitor this repo. Closing as 7.0.96 is out now and this is probably not an issue.
