### ISSUE TITLE
meta.json not updated correctly for 2.0.46

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-SVG#2]
Not sure what broke in the build, but the meta.json did not update correctly. Fixing it shortly.

**Comment by leMaik** [comment]
@Templarian Any update on this?

**Comment by Templarian** [comment]
@leMaik Just remembered about this, yea I'll work on this tomorrow. Completely forgot about it.

**Comment by leMaik** [comment]
@Templarian I'll just use the filenames instead…

**Comment by kaermorchen** [comment]
Is there any news?

**Comment by leMaik** [comment]
Still no news :disappointed:

**Comment by Templarian** [comment]
I have this fixed, just need to a release. The new meta.json includes a lot more data we've been working on getting ready for this next release.

**Comment by Templarian** [comment]
@leMaik Can you look over `v2.1.19`. Let me know if it looks okay.

The webfont release is going out tomorrow.

**Comment by leMaik** [comment]
@Templarian At least it is the same file this time. :+1: Looks good to me!

```
$ curl -s https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/meta.json | md5sum
f7c9714eae94a14660facbd14a81ef34  -
maik@athlon-elementary:~
$ curl -s http://cdn.materialdesignicons.com/2.1.19/meta.json | md5sum
f7c9714eae94a14660facbd14a81ef34  -
```
