### ISSUE TITLE
arrow-expand-horizontal missing in meta.json

### ISSUE THREAD

**Issue by leMaik** [Templarian/MaterialDesign-SVG#4]
The title says it all, [this icon](https://materialdesignicons.com/icon/arrow-expand-horizontal) just isn't there. :open_mouth: It's also missing in the `svg` directory.

Related to https://github.com/TeamWertarbyte/mdi-material-ui/issues/6

**Comment by PeterShaggyNoble** [comment]
It will be available in the next release.

**Comment by Templarian** [comment]
Closing this out as it will be addressed in the next release shortly.
