### ISSUE TITLE
Why doesn't this just use the mdi npm package?

### ISSUE THREAD

**Issue by RavenHursT** [Templarian/MaterialDesign-SVG#5]
Couldn't this just use the mdi package?  It seems out of date for some reason.

https://github.com/Templarian/MaterialDesign-SVG/blob/master/svg/reminder.svg 404's

While the icon is clearly available in mdi: https://materialdesignicons.com/icon/reminder

**Comment by RavenHursT** [comment]
Looks like this relates to https://github.com/Templarian/MaterialDesign/issues/2859

**Comment by Templarian** [comment]
https://materialdesignicons.com/history

Working on the release right now to get these packages updated to the latest.

**Comment by Templarian** [comment]
Just to clarify, we version the packages here and in the webfont to prevent breaking changes. For instance this release will have two renames and several icon redesigns (along with many additions).
