### ISSUE TITLE
Add mid.svg to the npmjs package

### ISSUE THREAD

**Issue by un33k** [Templarian/MaterialDesign-SVG#9]
[x] enhancement request

It would be great to also include [mid.svg](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B) in the npmjs `@mdi/font`. Or somewhere else that is `npm install`-able.

It make life much easier for `npm` upgrade and automatic copy of the `mdi.svg` in the `/assets` directory on upgrades.

**Comment by Templarian** [comment]
I don't watch this repo, so didn't see this until just now. Assuming you found it earlier, but we publish it under the `@mdi` organization as `angular-material`.

https://www.npmjs.com/package/@mdi/angular-material
